In [4]:
import numpy as np
import torch

1.	Нахождение сложной производной.
Найдите производную по x от функции:
 
При этом надо пользоваться встроенным в PyTorch autograd.



In [136]:
def f(x,y):
    c = np.exp(3-x**2)
    g = x**2*np.exp(x**9)
    m1 = np.tan(x)* x**2/y
    m2= np.log(c + x**3*y)
    m3 = np.tan(g) 
    return np.sin(m1+m2)*m3

In [137]:
f(0.5,0.4)

0.012011480952420241

In [138]:
def find_x_derivative(x, y):
    a=torch.FloatTensor([float(x)])
    a.requires_grad = True
    b = torch.FloatTensor([float(y)])
    c = torch.exp(3-a**2)
    g = a**2*torch.exp(a**9)
    m1 = torch.tan(a)* a**2/b
    m2= torch.log(c + a**3*b)
    m3 = torch.tan(g) 
    L = torch.sin(m1+m2)*m3
    L.backward()
    return a.grad

In [139]:
find_x_derivative(0.5,0.4)

tensor([-0.2560])


2.	Нахождение косинусной близости
Вам даны две матрицы A и B. Необходимо посчитать косинусную близость между строчками матрицы A и столбцами матрицы B. Ответ - матрица чисел, где номер строки - номер строки из матрицы А, а номер столбца - номер столбца из В, от которых бралась косинусная близость.
Напомним, что косинусная близость двух векторов - косинус угла между ними. В n-мерном пространстве косинус угла между векторами удобнее всего через скалярное произведение:


In [142]:
A = torch.randint(10,(3,3))
B = torch.randint(10,(3,3))

In [143]:
A

tensor([[7, 9, 0],
        [9, 0, 9],
        [9, 4, 2]])

In [144]:
B

tensor([[5, 0, 5],
        [8, 5, 0],
        [3, 0, 4]])

In [145]:
A@B

tensor([[107,  45,  35],
        [ 72,   0,  81],
        [ 83,  20,  53]])

In [ ]:
def get_cos_sim(A, B):
    